// Generated by Wrangler by running `wrangler types`

interface Env {
	MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
}
declare module "*.html" {
	const value: string;
	export default value;
}