// Generated by Wrangler by running `wrangler types`

interface Env {
	RELAY: DurableObjectNamespace /* Relay */;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.js" {
	const value: string;
	export default value;
}